FROM pytorch/pytorch:2.4.0-cuda12.1-cudnn9-runtime

WORKDIR /app

RUN apt-get update && apt-get install -y \
    git wget libgl1-mesa-glx libglib2.0-0 docker.io \
    && rm -rf /var/lib/apt/lists/*

COPY requirements_feedback.txt .
RUN pip install --no-cache-dir -r requirements_feedback.txt
RUN pip install --no-cache-dir git+https://github.com/openai/CLIP.git

COPY feedback_train.py .

EXPOSE 8001
CMD ["python", "feedback_train.py"]
