---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-secret
  namespace: photoprism-platform
spec:
  encryptedData:
    DOCKER_HUB_PAT: AgCcQU+Q6zXQegBBqPJKxZL5h/YH9K6jv+wD2Ja3+v3EZGt7a3CpIXNUa5k+mHerv8x4Oy+k4423DDoW6n0A4soI0FaUWesiKTdFTODuiBBGbuLaH3x/by78YJYiUeotHs2dnw2gjsOFBIhk5xG32cDGV1jr7P9/kwOODnrKw+b4JVE5Xz5mslg71zvV2PLRdKH/I/zf6XBve1IVUCnJ9hkS8WIJyvaXRiHRRjf/4iauINLKO+dEu60RIlxqvJJyFEPkRzo8KjEFswn4yRe4USSPLo9auFExkO16ERNF6QZxqC65IVgl3lPwtwbS9rLLPX8e90Jcqf4SsF4c8m69OI3tRD7K/4sVEhSONnApkMERu/pbJhu+lPFmyZwphu0QU4QF+VlXWZv0RMxfXg2MQdgbxrz0S5vpNEFSV53jCiCu7gWsv847VBCC0ZcEJV0nhA2wEzNTnPjT2aS/HEkB5IfMfEjjoTg0R0JwbSgajRLwBQgHtpXh1ZmPJSW8yVEdQGujKkycNLiHLK7U5riOiJwmBdgCAMHNoQo8/5Y5EGiqv0TVSsX67n+Ih2+8yidhxnW8sngd1O6IrJpKxIRiPkjU7WObJftHMGoGZ8m4SgQeI3Qb18QEDmOrlEN+VSkd15GVZcvJTbyK2faALzmUTzMnruk2/CNztY1bahjpZEhKnokcEptsyiA/Tm27199JfXklE6kkpBljNLoO5mIm1500gRuWUgYTbS48d498RR2RUeI8BEA=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-secret
      namespace: photoprism-platform
