---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: search-api-secrets
  namespace: photoprism-platform
spec:
  encryptedData:
    PG_DSN: AgB+H+xT1YMxDgwFMfyFWPjIfCC6lx1BCSXcnJVpDViKJEXPwWWbVuLzgrlRuZ5rX/7exoL74uzsB9oTwn8MG/M24nk9/KcSagzlITmnVbq/xfRHKpqXDSAt1t2tsE2QDPT1ELqOnK9DM++HartjkN4gupxS94V+QLoszAhtxoc/5u1CD39Zd70bMpDsTCzTkKnYGazURyhFujNK8cJrsUp8JvEKz5EOmVtMjh6y26852C3PeFrxlZ/s/hLPG7eHsM9Ax8frIjz/veDFKxscvSxbT6jkbTOKyDkiP6LEPZPNmI3tLyaAbUp1SDj5CNSGFwXTRDkLd/PHqdztotqlhR8ZN+jeHeghVJF6U2yJmjY7xRA+fZLtAXOWS1nz6QtVqfAitpRlpRQCcMklNxL/vIWmV8wpwm6C5BsskSpqw2/GKfH7XhzNT1BlyDh+vQE4Tf6hAipPoSvAB5Bd2iR2nI44VUXxb5O1m0NHXeqYzS/iNbeU2QV8D4Nc3yuWBF5ca58pk0PEJjqhobkZAbiJ+x4pnyZ2q4Mwzv0Hou0T5R1V8uCTFvYfPLZex3CQS6DEq33beHd424k8KAwyBBfY97UXINCtkqbyocTpGWXyG0k9x2DSmMAteNOPpdsO1V8hWaLk3AaqY+C57qijpwdkfr2fBYEA5oxaXdj8+rmNuO/B9eZtLY1Kcr8323Vl+22BRSYPn6ypfgVIWsMp9NKsVwyODVSLEhU+yNL45TNSqjr+8rkKAk+oM03HlUJLWvM5MkUj/BQoL/lNupXBhEUBTkKluUbzpjIPz8qrAfiwUHFMw2A60krqQf5/QQKf1/BdTIwvml6FBiqJL4xbdA==
  template:
    metadata:
      creationTimestamp: null
      name: search-api-secrets
      namespace: photoprism-platform
