---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: search-api-secrets
  namespace: photoprism-platform
spec:
  encryptedData:
    PG_DSN: AgBGj9zZ4Uxo0dUyG8SWC5Xq3xDK1qoSXUFvslG2Ln/4+Jk+P/rHiu+3ZNdQ69GJXNkS6silSpB4PqM9e+AefJCkobqNET3V2tZAdUwbwNu+NALmih8noUk9KYqZ5AmVQ/3Yhne72CHhY0pa1WLXP/lfe8uhlSjXIeAyewLY7GJO2TvkSLQDUzgPX5Rno1uSdtFaQzwMEdbuZTYV1gxSs4ceHZR86IgnVIIlrTwx/vecwr7Wfgj8B4pw0IJYE5Ql+eFBRra7JdfkNFjPauJg5fusHH0DzE6zAWezANW33i1GeYFJnNuq3ZdVO1XHzAckpqQi+g7IHRk+hbwABhjEh6W5NFOqx/oMqP/AbRNvDaKQpD2RIbBrd+e+8wSOPOAeRhhM7Frj09LLUkhxzGxfWfgpVsTDxYYSP1CqTZQgu8YByKkf0FDS3/t89lVfYCiqZVZGRcnqxkx8iDXRxxU5vvbOhgkzsmysivULTFC7i2LXi+nzgj3hIEYgbHu8bSJLTDtX9ZMSY7ouxZF56RK62TE6EwTqsPfDmNJagfGy5w/KoDfwSUTGjUFSS/ehKKv+247ndC/+UoDk/z2GjK+iCWk7dIpkO56sQLCoAlO4jj5Qug4oiNV1N1kWXG1kqOXLtn815xhpa6Sa2MpwviYx2mdAOdNRBYCsfKeJaTA1OG2ugC58JLK3m8kOtZIK+3OIrwBMiNVUXeCJop7A5qjLp2+iKBwNUNAeAlV/ksdpF5AKaGkdzbz9Ap7STMTnbBCvLguW6KuNX7RiiJ0tjhwkQlQ6dk5zBQ6cxxhKa7QSWSwi8aO/65iyxVmpnRzXJz7QtZEPGiiRBXKAAPQ=
  template:
    metadata:
      creationTimestamp: null
      name: search-api-secrets
      namespace: photoprism-platform
