---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: photoprism-webhook
  namespace: photoprism-production
spec:
  encryptedData:
    INGEST_WEBHOOK_SECRET: AgC7TnRgF5uC6DKpfUAT+G2jDSJWRzI76hC6KwBJM1ZuQbxgfE7YxplveO2XuIFwiLnJmOCV17PQekQZtnX4HwSkR0iIbwdVUIwk6E+xilcbLpGCyIH/MeLZdfNEXiu7q0Vtt9Z+3ISv/aeqtxXf66pzWpqYFHcAU4P48zOtXeedXQNpbUVgfCnb4sgZFNVjS/Z5RSQzrPDnQTN+v28pVCHIR/KgApd1OtIbR9sbidoKYqVewxJHbnexB+GVdEnQ8Wwe0AFisZeNYyTeFXEtrLjoLKXe0tia7teYtxTc63iNrhIN8UmEgBu0tQZGTNpzYq/WMJKWe4u4P955bzRx24QuHMLs+m3q3hYHsT+fvsbALheUsQi46lWebYZwTYkWAz29nJ2afBNNfMmyWCH//0AkPlb125ffbtcaCJbEOB8FKcqm2SEmd7xeA1jHWlM1iXTa+0A5r67MvFcrIYMpS/i8/vHTp/zo9daaB+px7Mq1CLPp2U+mzG+kYXsblVRBGWBDWADTAypbjxTSRDNdpW7YD7mznoPjTRqHTgtjh9a9gyyKNZ4j5+1Axi1eYBPweaKTFbfrUaIRYT7cPqjC6oVHV/Rtah5/aMHnqcn+5phm/5OGXHBS6rjFYven8WUNhcWeoqO6YJGfhIWX6w876b/ab7pS4tU3Rw2pgHEh9noUxjdJPgnWcbtX6prA4WwLJxXGTg9jeeTknLVb8f3ChIe6GJOWmZrs9fIG5I0de3dzpKWQVSEFmQSjMzQjmW/qbdDHm0Ls0OQOkG+Qt53Cent8
    INGEST_WEBHOOK_URL: AgBV35KoRsMaPTuBv7DgV27oJmS7Yg7WZIetXc/an9J8wl/li1rl9lTmw4cI8MH8KQA9gG2R/MUqCNPzLBOnMMrAF+UyxSDSero5DWrfPOid6A145yF3m7bxExMxeNR9DA62T92TOT1EWG87MO0Pbf9X8c8S7j5KVzPelL84NJPOV2Hz22vo3PU0bvn1g3vhrlSTbF4CEkAJogyU2Qm46KSrVmaRml/61FsAY9zB9bi20ybGNgbxt0vlUllMox8+a6C+e2aw934NIwBruNGEaVAHF306gCnGQZFTjBkTSwZkiPM6ZCZoTZL5IRzD+IgWUN1Df3noAdWjgIiCcui8H0XELQ45OwqUchTTDRe0sffjRuNdnKtrmuDY1Gw//V4T4qHFrW0MgX3T+DL69jqmrSPvWUnTyGsriYSiSJYvJDwWfXwGRm/ln+NOMLwNV+w0ba8CafhJYE0RLbjyOCdfm0ci8Gks5fQU3GWFC4qKAbLoBtS+sO1sL4JJG2k3FpLlOxCbSKTMuDiMbXcKFk1SaH95MvMzk46dkdSZblITPrOEFGhbrSV0sGWJaGbImvCVIAvjf7nNTqyPSRaiKDV8UnINSe4HgbppgJAEBciklb2waDgvHSrU7Ms9n7vQL9fjeh5mX2WAp2mapTQukr1ISlaD+aflHh9MZKMnc1aHoqWICSWAk4/B8rgH9QAy8rjPGz7UE1whU5OsWMp6a+yyYRNWHVqvxdqQrA0INgDENH925+MaunrljXPYwlbs91/EG8SxN2G5yF8pXP2YatIUIDHeZg==
  template:
    metadata:
      creationTimestamp: null
      name: photoprism-webhook
      namespace: photoprism-production
