---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: photoprism-webhook
  namespace: photoprism-production
spec:
  encryptedData:
    INGEST_WEBHOOK_SECRET: AgBeY17S+kOejy2KyfrpDODwfO0p6REX3wHA2PbkBYt4ZygRFWEmJ7OFtQ2jL1i+p8o3PkuHQEe58mJZGi7/kKVEypTTv+BiZJWhTXUFTqR0UjqHX0a7NAN/h+hTtd9Gi9bAzMg6fW01OOEFAEFNyjo+wxMlW3xFkUF2Ueof6ppBPHg/1nGuZYE4z7ok91yGodReyTUbKyLioeiW5UDNGKR+/an5XYN+iDRGUXHqssPLctQfP3GrntkV0tAGNcz5b1opr+ANXzm+RR4sTiWOpNwVg14xNWVYo4o45Z1Q2EJ7JM8C8KAd3FJnbke4j6I/b1cNEdyKl39WNJQnKVUHKkp5PxEA1blCZgDffdQ8f02dn7cFIEbVqxipXvyN0AvAqrukEBnkqrIWbUGqootseb+V4oFIwX+l4ytWyT5v8uHy8xfGbaO1e1a22pRHI5b5+PSJtAr/RDgCU4rtA/hX+oImwdAWTnKt6apc+Wzm06oWUXzkreiicSPlfKvHCbUFcKmmSsFqjquayqcwg9K5ZcFSUXM8Eclz2aga31QYUX9CcNFr+yfuZwI4yj929NcFH4gTHhpKwMdKB35VQq5qE3HiMBovLG8kJYf2R6mLcC7K+u5hPufaSr78rvh39fOu/kcfSk5dzD6/3SSsDzydfy45+nyjxMaMder/dW0bQv+4m7GCEA3txkogMBYESICishIJEESWn3G+NnyeX2mSdZTlcyIIh7jMGU2prkQ=
    INGEST_WEBHOOK_URL: AgB5cZUB2KLiXbE9L9Bxf77Myhle7Y9pXyAZRZyRTV+eyK9sjdqET/gnE3u81kjOK1meFyzIIE1Ghhnp+wqX7wjTglxxy6kW5yf7gbOEEldKOYNzNXJ9v7rl4k2hZYMcHOONTjsTrV3FQMmLgFCRCtlIkp1aY9tnAWn7x+aLOOhCK8f/RrmeEWY89mk6O6Ps9mmJvDkfQGATxPIoIePyAl45/MjGIW2PZQX62USmm8cCElArhOdwSJfgDdhkdU1dtgiuk9PClrJNlwLVB6fW5DGXA5dM2pu9s7XiDIAMh7rAgjxmQd9fe6KPECczzex36dmHYYQWDsAkMr7GjRQS/BRNWqiRYIFaXBvkZN+td7e1aZjg3mT/ytEKC1ad9pYefOq+Jno+KOSwuEkdUzyyw6VmWfi7RpnbmBdojPv4gOVWUZ72BeFf9zirLddfHFD72YTB2pN2Gm3OW0dEO4Qx4UisJBUGQ0bki4tBBYzNtGVPS6ICGm7yHoH6ZgV4H5XeqjvAbUso4JImS+6Rw+4qdQAGLT8iXwoszY5FXLixAj58tZ5MYaDLKon+WQkeziIw1kE9N6vt/ct/7UG2Kyuv1KDCE1w3sNlycg4XdIvpXeX7ABv/LVbLF/XWxQnUEb3CETWGJltopJtF5AXJ7R/y50AiKCko1MhHwnavxDP1yICDocECN10SPNIcjwlp1q0Ee9DW5hByk1N3doTO8XBMFgUeKngMyO1A5SdqKABFy1wqGLhYDG8Og6FFzxCsDbDIBi8bseOJzGfux/xRnJkS/gy8ZQ==
  template:
    metadata:
      creationTimestamp: null
      name: photoprism-webhook
      namespace: photoprism-production
