---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: internal-token
  namespace: photoprism-platform
spec:
  encryptedData:
    INTERNAL_TOKEN: AgCr3OKlWHG0Pgh3vFbJAzmHglAUr8dLYWQ+z01sZfInUlqSju9gDxzM/D6xOKL2SoSaYZYEue1FR4MfeJpWNLULpk0p3mH6AsbEXDGX1lzjpiFfgkU/FpOQHDM+45Dq1HWuuzcPdEKxzb2S61i9aDByfH2eK8Rsy+o3PEAMRxb389K2zpZmJ+Gk3XXV8FYy88nntyknsmVUl/I9LH52OAnauzTpirn3XIXCmJefR1P0Cz0rS7SwYSrjvmIMmPfRYgdtHCGSkdFWnfyb6gGInbwuZbnHwSKi33DtTnBqUL+PmJY35iZ8dqp9hZQLABqmz42PAqqzOfGhK4u/WfEwoVVVwPhlGja2MUQ/p8vK/t/vfDuE1El/kJ5+3/bZeOFDDj4Y0TJ7nh7cCdd8INSEZP0TRUDGM/dg/zsSKT1r4pS9jdqT+C5KasgVIF7ZZmqe1JcsyPml3YPUyJQvJ6kRtbuZgBXwXpKTONy40xrIMIkL9aVD3cNNukVkigjaT75fZjCMv6clsU62ivt29zF9mUIdJm0gf/ZFrVQqVrOi1NRARstMh7tZ53IUR4OkrYK/KJeEO9WAZoe6/5K8wHf5yLJUCHV75V5lDp4N+oAl+PkeN/V4EQKU7RT6kCNka+TRAUGnu0dqu5EHeauyzaiBLcs+y0/Uujx4mDZdUr8zVf8Y3bV8VIzXe7euYx1JCOA4T+60nQZ6+BV0zhI9r/bhwjzv17sN1Ungi4PfQKHzDAChuvc7dCreaQvWol3sc0DT0nBLuexSW+k1EA2ZXRlr2WRt
  template:
    metadata:
      creationTimestamp: null
      name: internal-token
      namespace: photoprism-platform
