---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: internal-token
  namespace: photoprism-platform
spec:
  encryptedData:
    INTERNAL_TOKEN: AgDFdnMjwySblxT2u7K6fbyjHyMfiD0gx1RfegGASm/JsikFxiVRwMRgl5iS0c0fKP41IFsh0FnWbRTssVscMdonTs3M3VHY0JroWKdvVP+ZiUk0g4fnzUfB6G9V9VNu5C1qNhiJfX1nxygdPYW6FOx4cCoQjZ+xbVMLKXSvTjXY60kwYCTc/J+O5rQkmM/T//Sqh5Y7DzQm5Sxx9pNGSlm3WVqdN0b0MfCn7sRgbF7zuiz1mHdnCjF7bPj8rmvZFnzXFuzofRi59wDv2A21HeVx9FheeyDSnloT9xmPZL1rpMcCBDrpEqCHfQr7+fDL52uH7bNho0O64SN0BQJ3z0OUjXQ9aqmQrGK/p708TKGg78PZQ+UnXRQNVTUzlukXFUxi6rRJaNm0nYxUbSKN7TRMUjvoYyqq7MXuVzeEHvJNPmrjSiRsbqvMtOxngZOOJLzzjN/ha7F0USmZKNQNwKxKtcQWPt7UAgwVVJ7WKa2CTLLzgal6tvSWfLajeRRzBXGOZCZG0jKy76GwAMCU2fuZBToScekpOq7cPPDpc5pYzs51XE+ZPylxJCKVbRVYXNnauzFeIvjYCUrcM3GBdjz2JMfGai31qAE7TGLrkefsmMrSwoe3J6W9L8t54pIYzxAlJhJfGHOZ/Sd5OtFiz0hbrsUmo7JcvlcEDShW+AoyUcakvbIYIYGCpVQaMbu7UD/GXw5g4XvI5jVwaQK1VBJopWiSdOEKSB1DpQ==
  template:
    metadata:
      creationTimestamp: null
      name: internal-token
      namespace: photoprism-platform
